language: objective-c
osx_image: xcode9.2

cache: cocoapods
podfile: Example/Podfile

email:
  on_failure: change

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/BubblesView.xcworkspace
  - IOS_FRAMEWORK_SCHEME="BubblesView"
  - IOS_SDK=iphonesimulator11.2
  - IOS_EXAMPLE_SCHEME="BubblesView_Example"
  matrix:
  - DESTINATION="OS=11.2,platform=iOS Simulator,id=9C4C0DDA-839D-4851-AA09-4382DB814A63"  SCHEME="$IOS_EXAMPLE_SCHEME"  SDK="$IOS_SD$

before_install:
- gem install cocoapods  --pre --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild test -workspace "$WORKSPACE" -scheme "$IOS_EXAMPLE_SCHEME"  -sdk iphonesimulator -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
